Add code for Hamburger menu icon
Amanulla/Portfolio pull request #5
Opened 2022-06-22 10:48 UTC by Amanulla

Here I added code for Hambergar menu icon, and added menu items like 'portfolio, about, and contact' 
I gave Id's for three menu items, because when the user clicks on the menu item then it will scroll the webpage to a particular point.

2022-06-22 13:45 UTC, vechicin requested changes
# Hi @Amanulla ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Proper mobile menu implementation 
- [x] Nice transitions!

## Required Changes ♻️

- [ ] **NOTE FOR FELLOW REVIEWERS**: Stylelint checks are passing locally, please do not invalidate submission do to Stylelint errors

- [ ] Your desktop version is not working as intended. Please fix it. I am using Google Chrome, for reference.

<img width="1440" alt="Screen Shot 2022-06-22 at 8 44 07" src="https://user-images.githubusercontent.com/82426682/175044173-ce7f65c6-9d70-4481-8b16-f5ccdc194254.png">

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 13:45 UTC, vechicin commented on hamburger.css
> +  }
Your mobile menu design doesn't quite match the template design.

Your design:

<img width="186" alt="Screen Shot 2022-06-22 at 8 38 50" src="https://user-images.githubusercontent.com/82426682/175043026-e6947739-8cb1-4a89-90a9-1e55f0f86231.png">

Template design:

<img width="153" alt="Screen Shot 2022-06-22 at 8 39 16" src="https://user-images.githubusercontent.com/82426682/175043111-25d58363-f63c-498d-957b-2940fb9e14a2.png">

Please fix the font so it matches that of the template design.

<img width="843" alt="Screen Shot 2022-06-22 at 8 40 16" src="https://user-images.githubusercontent.com/82426682/175043308-58c6fa0d-41c2-4283-a629-defd1ae1579e.png">

Additionally, according to the principles of mobile-first design, you should only use media queries to make a mobile version responsive to a desktop version. This media query is doing the opposite. Please remove it.

2022-06-23 14:24 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Amanulla , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 14:24 UTC, leonardodiasb commented on hamburger.css
> +  }
- [ ] Your `font-weight` still does not match with the Figma template. Kindly change that as the previous Code Reviewer pointed out.

2022-06-23 14:40 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Amanulla   

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 14:41 UTC, merged