Wrote code for popup menu
Amanulla/Portfolio pull request #6
Opened 2022-06-23 21:01 UTC by Amanulla

### Popup Modal
By doing this activity, I learned how to make popup modal windows and style them to look good. And I learn how to set Attribute and how to get Attribute in javascript.
- I wrote code for Modals for mobile and desktop versions.
- Added a few lines of javascript to popup the modal window.
- Added some style to the particular Modals to look better.

2022-06-23 21:33 UTC, tresorsawasawa reviewed
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Amanulla 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that requires [pair-programming](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#:~:text=You%20should%20implement%20the%20above,and%20submit%20this%20activity%20individually.) but I noticed that the current PR has only one contributor. Kindly make sure your coding partner has some commits in your pull request before requesting the next review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-06-24 07:54 UTC, zieeco reviewed
# STATUS: INVALID!!!  :x: :x: :x: 

Hi @Amanulla ,




While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure you implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._

- [ ] As it is a requirement for a project that students should not edit the linter file as you've done, please kindly remove all the linters files you have now and copy that of the [microverse html-css-js](https://github.com/microverseinc/linters-config/tree/master/html-css-js), delete the node_modules file and install them using npm. that should update all the linters.

- [ ] As it is a requirement for this project, please, kindly make sure there are no linter errors.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **Does not count** into the code reviews limit._
# **INVALID PROJECT**

2022-06-24 08:04 UTC, zieeco reviewed
# STATUS: INVALID!!!  :x: :x: :x: 

Hi @Amanulla ,




While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure you implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._

- [ ] As it is a requirement for a project that students should not edit the linter file as you've done, please kindly remove all the linters files you have now and copy that of the [microverse html-css-js](https://github.com/microverseinc/linters-config/tree/master/html-css-js), delete the node_modules file and install them using npm. that should update all the linters.

- [ ] As it is a requirement for this project, please, kindly make sure there are no linter errors.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **Does not count** into the code reviews limit._
# **INVALID PROJECT**

2022-06-24 11:24 UTC, Lucas-Masaba requested changes
# Hello @Amanulla  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.


## Invalid Code Review Request ⚠️ 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-24 11:24 UTC, Lucas-Masaba commented on index.html
> +        <!-- --------------------------------------------First Modal--------------------------------------------- -->
- [ ] Please remove all the comments that look similar to this and run `npx hint .` on your terminal. This should fix the error. HTML comments should be written in this format `<!-- Comment -->`

2022-06-24 11:45 UTC, Lucas-Masaba requested changes
# Hello @Amanulla  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- For some reason, when I run your project live, it does not run on my browser and so I cannot check the popup functionality.

2022-06-24 11:45 UTC, Lucas-Masaba commented on app1.js
> +}
- [ ] According to the instructions, you are supposed to use a javascript object to store information for all projects as seen here. Please fix that 👍  
![image](https://user-images.githubusercontent.com/45460192/175527532-91e198ab-00e9-40aa-bb3c-f6656bfed000.png)

2022-06-24 19:13 UTC, ishimwezachee approved these changes
Hi @Amanulla and @Lucas-Masaba , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/SVH9y2LQUVVCRcqD7o/giphy.gif"/>
## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 19:18 UTC, merged